#haproxy_version: 1.6.3
ssl_path: "/etc/ssl/carteloisirs.com"
cert_name: "staging.carteloisirs.com.pem"
haproxy_front_ip: "{{ ansible_facts.ens20.ipv4.address }}"
haproxy_adm_ip: "{{ ansible_facts.ens18.ipv4.address }}"
backend_server:
  jboss:
    - { name: "front01.staging.s1.carteloisirs.com", listen: "192.168.10.18" }
    - { name: "front02.staging.s1.carteloisirs.com", listen: "192.168.10.19" }
  cargo_html_site:
    - {}
haproxy_adm: haproxyadm
haproxy_adm_pass: "{{ vault_haproxy_adm_pass }}"
